name: doctorapp
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=3.0.2 <4.0.0"
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  connectivity_plus:
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.3
  flutter_svg:
  google_sign_in: ^6.1.4
  country_pickers: ^2.0.0
  flutter_svg_provider: ^1.0.3
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.3.0
  pin_input_text_field: ^4.5.1
  colorful_safe_area: ^1.0.0
#  intl: ^0.18.1
  pinput: ^2.2.31


  # health
  cupertino_icons: ^1.0.5
  #  motion_tab_bar: ^0.1.5
  google_mobile_ads: ^1.3.0
  app_tracking_transparency: ^2.0.2+4
  launch_review: ^3.0.0
  flutter_mailer: ^2.0.2
  page_transition: ^2.0.9
  step_progress_indicator: ^1.0.2
  url_launcher: ^6.1.5
  flutter_share: ^2.0.0
  auto_size_text: ^3.0.0
  fluttertoast: ^8.0.9
  photo_view: ^0.14.0
  flutter_cache_manager: ^3.3.0
  path_provider: ^2.0.11
  rxdart: ^0.27.5
  numberpicker: ^2.1.1
  http: ^0.13.4
  #  flutter_pdfview: ^1.2.5
  package_info_plus: ^4.0.1
  flutter_screenutil: ^5.7.0
  flutter_rating_bar: ^4.0.1
  get_storage: ^2.0.3
  pdfx: ^2.3.0
  flutter_staggered_animations: ^1.1.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter_icons:
  image_path: "assets/images/AAWI LAUNCHER ICON.png"
  android: true
  ios: true
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/
    - assets/health/images/
    - assets/health/pdf/
  fonts: 
#    - family: Proxima Nova
#      fonts:
#        - asset: assets/fonts/ProximaNovaBold.ttf
#          weight: 700
#    - family: Avenir
#      fonts:
#        - asset: assets/fonts/AvenirBlack.ttf
#          weight: 900
#        - asset: assets/fonts/AvenirHeavy.ttf
#          weight: 900
#        - asset: assets/fonts/AvenirRegular.ttf
#          weight: 400
#        - asset: assets/fonts/AvenirMedium.ttf
#          weight: 500
#    - family: SF Pro Display
#      fonts:
#        - asset: assets/fonts/SFProDisplayBold.ttf
#          weight: 700
#        - asset: assets/fonts/SFProDisplayRegular.ttf
#          weight: 400
#    - family: SF Pro Text
#      fonts:
#        - asset: assets/fonts/SFProTextRegular.ttf
#          weight: 400
#        - asset: assets/fonts/SFProTextBold.ttf
#          weight: 700
#    - family: Manrope
#      fonts:
#        - asset: assets/fonts/ManropeMedium.ttf
#          weight: 500
#    - family: OCR A Extended
#      fonts:
#        - asset: assets/fonts/OCRAExtended.ttf
#          weight: 400
#    - family: IBM Plex Sans
#      fonts:
#        - asset: assets/fonts/IBMPlexSansMedium.ttf
#          weight: 500
#        - asset: assets/fonts/IBMPlexSansBold.ttf
#          weight: 700
#    - family: Outfit
#      fonts:
#        - asset: assets/fonts/OutfitRegular.ttf
#          weight: 400

    - family: RobotoCondensed
      fonts:

        - asset: assets/fonts/RobotoCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 300
flutter_intl:
  enabled: true
